/**
 * ***************************************************************************************************************
 * Personal Weather Station Plugin for FM-DX Webserver (Server JS)
 * Retrieves data from the WeatherUnderground API.
 * Modified version of the Weather plugin by NoobishSVK, updated for compatibility with personal weather stations.
 
 * !!! DO NOT EDIT THIS FILE !!!
 * To configure your API key, station ID, model, update interval, and display options, please edit:
 * --> plugins_configs/PersonalWeatherStation.json
 * ***************************************************************************************************************
 */

const fs = require('fs');
const path = require('path');
const https = require('https');
const { emitPluginEvent, getPluginsWss } = require('../../server/plugins_api');
const { logInfo } = require('../../server/console');

const pluginConfig = {
    name: 'PersonalWeatherStation',
    version: '1.0',
    description: 'Real-time display of personal weather station data via the WeatherUnderground API. Modified version of the Weather plugin by NoobishSVK.',
    author: 'Lucas Gallone',
    frontEndPath: 'PersonalWeatherStation/weather.js'
};

const configDir = path.resolve(process.cwd(), 'plugins_configs');
const configFile = path.join(configDir, 'PersonalWeatherStation.json');

const rawTemplateWithComments = `{
// For more details regarding the configurable values, please visit the plugin's GitHub page.
// Note about the API key: It is valid for 6 months from the day it is generated on WU. You will then need to regenerate it.

"stationId": "", // Your weather station ID. It can be found on your WU public page.
"apiKey": "", // The API key for your station that can be found on your WU account dashboard.
"stationModel": "", // The make and model of your station. Will be displayed to visitors. (Optional)
"unitSystem": "metric", // Use "metric" for metric units, otherwise "imperial" for imperial units.
"updateIntervalMinutes": 1, // Update interval in minutes when at least one user is connected (minimum is 1).

// Additional weather values in the plugin details display. Set to "true" to show, "false" to hide.
// If all values ​​are set to "false", only the temperature will be displayed and the details tooltip will be disabled.
	
"display": {
"pressure": true, // Display of the atmospheric pressure.
"humidity": true, // Display of the relative humidity.
"dewPoint": true, // Display of the Dew Point value.
"heatIndex_feelsLike": true, // Display of the Heat Index / Feels-like temperature.
"windChill": true, // Display of the Wind Chill value.
"windAverageSpeed": true, // Display of the average wind speed.
"windDirection": true, // Display of the wind direction, in degrees.
"windGusts": true, // Display of the wind gusts.
"precipitationHourlyRate": true, // Display of the hourly rain rate.
"precipitationDailyTotal": true, // Display of the total rainfall for the day.
"solarRadiation": true, // Display of the solar radiation value.
"uvIndex": true // Display of the UV index.
}
}
`;

let hasWarnedUnconfigured = false;

try {
    if (!fs.existsSync(configDir)) fs.mkdirSync(configDir, { recursive: true });
    if (!fs.existsSync(configFile)) {
        fs.writeFileSync(configFile, rawTemplateWithComments, 'utf8');
        logInfo("[PersonalWeatherStation] The plugin is not yet configured. Go to /plugins_configs/PersonalWeatherStation.json to enter your weather station's ID and API key.");
        hasWarnedUnconfigured = true;
    }
} catch (e) {}

let inMemoryData = null;
let lastFetchTime = 0;
let previousPressure = null;
let pressureTrend = null;
let activePayload = null;
let broadcastTimer = null;
let fetchPromise = null;

function parseJSONWithComments(content) {
    const cleanContent = content.replace(/\/\/.*$/gm, '');
    return JSON.parse(cleanContent);
}

function requestWeatherAPI(url) {
    return new Promise((resolve, reject) => {
        https.get(url, (res) => {
            let body = '';
            res.on('data', chunk => body += chunk);
            res.on('end', () => {
                if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                        resolve(JSON.parse(body));
                    } catch (e) {
                        reject(e);
                    }
                } else {
                    reject(new Error(`HTTP ${res.statusCode}`));
                }
            });
        }).on('error', reject);
    });
}

async function fetchWeatherData() {
    if (fetchPromise) {
        return fetchPromise;
    }

    fetchPromise = (async () => {
        try {
            if (!fs.existsSync(configFile)) {
            if (!hasWarnedUnconfigured) {
                logInfo("The plugin is not yet configured. Go to /plugins_configs/PersonalWeatherStation.json to enter your weather station's ID and API key.");
                hasWarnedUnconfigured = true;
            }
            activePayload = { status: "unconfigured" };
            return activePayload;
        }

        const fileContent = fs.readFileSync(configFile, 'utf8');
        const config = parseJSONWithComments(fileContent);

        const apiKey = config.apiKey || "";
        const stationId = config.stationId || "";
        const stationModel = config.stationModel || "";
        const unitSystem = config.unitSystem || "metric";
        const intervalMins = Math.max(1, parseInt(config.updateIntervalMinutes || 1));
        const cacheDuration = intervalMins * 60 * 1000;

        if (!apiKey || !stationId || apiKey === "" || stationId === "") {
            if (!hasWarnedUnconfigured) {
                logInfo("The plugin is not yet configured. Go to /plugins_configs/PersonalWeatherStation.json to enter your weather station's ID and API key.");
                hasWarnedUnconfigured = true;
            }
            activePayload = { status: "unconfigured", intervalMins: intervalMins };
            return activePayload;
        }

        const displayConfig = config.display || {};
        const now = Date.now();
        const units = (unitSystem && unitSystem.toLowerCase() === 'imperial') ? 'e' : 'm';
        const isImperial = (units === 'e');

        // Check RAM cache using dynamic user-defined interval
        if (inMemoryData && (now - lastFetchTime < cacheDuration)) {
            activePayload = {
                ...inMemoryData,
                status: "ok",
                displayConfig: displayConfig,
                isImperial: isImperial,
                pressureTrend: pressureTrend,
                stationModel: stationModel,
                intervalMins: intervalMins
            };
            return activePayload;
        }

        const url = `https://api.weather.com/v2/pws/observations/current?stationId=${stationId}&format=json&units=${units}&numericPrecision=decimal&apiKey=${apiKey}`;
        const data = await requestWeatherAPI(url);

        if (data && data.observations && data.observations.length > 0) {
            const rawPressure = data.observations[0][isImperial ? 'imperial' : 'metric'].pressure;
            const currentPressure = (rawPressure !== null && rawPressure !== undefined) ? parseFloat(rawPressure) : null;

            if (previousPressure !== null && currentPressure !== null && !isNaN(currentPressure) && !isNaN(previousPressure)) {
                const diff = currentPressure - previousPressure;
                if (diff > 0) pressureTrend = "rising";
                else if (diff < 0) pressureTrend = "falling";
                else pressureTrend = "steady";
            }
            if (currentPressure !== null && !isNaN(currentPressure)) {
                previousPressure = currentPressure;
            }

            inMemoryData = data;
            lastFetchTime = now;

            activePayload = {
                ...data,
                status: "ok",
                displayConfig: displayConfig,
                isImperial: isImperial,
                pressureTrend: pressureTrend,
                stationModel: stationModel,
                intervalMins: intervalMins
            };
            return activePayload;
        }
        
        if (activePayload) {
            return activePayload;
        }
        return { status: "error", intervalMins: intervalMins };
    } catch (err) {
        if (activePayload) {
            return activePayload;
        }
        return { status: "error", intervalMins: 1 };
    } finally {
        fetchPromise = null;
    }
    })();

    return fetchPromise;
}

async function loopBroadcast() {
    const pluginsWss = (typeof getPluginsWss === 'function') ? getPluginsWss() : null;

    // Call API and push data only if clients are connected
    if (pluginsWss && pluginsWss.clients && pluginsWss.clients.size > 0) {
        const weatherData = await fetchWeatherData();
        if (weatherData && typeof emitPluginEvent === 'function') {
            emitPluginEvent('PersonalWeatherStation', weatherData);
        }
    }

    // Determine the next loop tick based on config
    let nextInterval = 1;
    if (activePayload && activePayload.intervalMins) {
        nextInterval = activePayload.intervalMins;
    }

    if (broadcastTimer) clearTimeout(broadcastTimer);
    broadcastTimer = setTimeout(loopBroadcast, nextInterval * 60 * 1000);
}

function initClientConnectionListener() {
    const checkWssInterval = setInterval(() => {
        const pluginsWss = (typeof getPluginsWss === 'function') ? getPluginsWss() : null;
        if (pluginsWss) {
            clearInterval(checkWssInterval);

            pluginsWss.on('connection', async (wsClient) => {
                // Fetches fresh data if the server was "asleep", or uses RAM if less than 1 minute old
                const data = await fetchWeatherData();
                if (data && wsClient.readyState === wsClient.OPEN) {
                    wsClient.send(JSON.stringify({ type: 'PersonalWeatherStation', value: data }));
                }

                wsClient.on('message', async (msg) => {
                    try {
                        const parsed = JSON.parse(msg);
                        if (parsed.type === 'PersonalWeatherStation' && parsed.value?.status === 'request') {
                            const resData = await fetchWeatherData();
                            if (resData && wsClient.readyState === wsClient.OPEN) {
                                wsClient.send(JSON.stringify({ type: 'PersonalWeatherStation', value: resData }));
                            }
                        }
                    } catch (e) {}
                });
            });
        }
    }, 1000);
}

loopBroadcast();
initClientConnectionListener();

module.exports = {
    pluginConfig
};