/**
 * ***************************************************************************************************************
 * Personal Weather Station Plugin for FM-DX Webserver
 * Retrieves data from the WeatherUnderground API.
 * Modified version of the Weather plugin by NoobishSVK, updated for compatibility with personal weather stations.
 
 * !!! DO NOT EDIT THIS FILE !!!
 * To configure your API key, station ID, model, update interval, and display options, please edit:
 * --> plugins_configs/PersonalWeatherStation.json
 * ***************************************************************************************************************
 */

(() => {
    const currentURL = new URL(window.location.href);
    const WebserverURL = currentURL.hostname;
    const WebserverPath = currentURL.pathname.replace(/setup/g, '');
    const WebserverPORT = currentURL.port || (currentURL.protocol === 'https:' ? '443' : '80');
    const protocol = currentURL.protocol === 'https:' ? 'wss:' : 'ws:';
    const WEBSOCKET_URL = `${protocol}//${WebserverURL}:${WebserverPORT}${WebserverPath}data_plugins`;

    let ws = null;

    function requestData() {
        if (ws && ws.readyState === WebSocket.OPEN) {
            ws.send(JSON.stringify({
                type: 'PersonalWeatherStation',
                value: { status: 'request' }
            }));
        }
    }

    function initWebSocket() {
        if (!ws || ws.readyState === WebSocket.CLOSED) {
            try {
                ws = new WebSocket(WEBSOCKET_URL);

                ws.onopen = () => {
                    requestData();
                };

                ws.onmessage = (event) => {
                    try {
                        const msg = JSON.parse(event.data);
                        if (msg.type === 'PersonalWeatherStation' && msg.value) {
                            const payload = msg.value;

                            // Ignores request messages sent by other connecting clients
                            if (payload.status === 'request') {
                                return;
                            }

                            if (payload.status === "ok" && payload.observations && payload.observations.length > 0) {
                                renderWeather(
                                    payload.observations[0],
                                    payload.isImperial,
                                    payload.displayConfig || {},
                                    payload.pressureTrend,
                                    payload.stationModel || ""
                                );
                            } else if (payload.status === "unconfigured" || payload.status === "error") {
                                renderNoData();
                            }
                        }
                    } catch (e) {
                        console.error("[PersonalWeatherStation] Parse error:", e);
                    }
                };

                ws.onclose = () => setTimeout(initWebSocket, 3000);
            } catch (e) {
                setTimeout(initWebSocket, 3000);
            }
        }
    }

    function renderNoData() {
        document.getElementById('weather-plugin')?.remove();

        const tooltipContent = `<table class='text-left'><tr><td>No data available.</td></tr></table>`;
        const $serverInfoContainer = $('.dashboard-panel .panel-100-real .dashboard-panel-plugin-content');
        
        const weatherPanel = $(`
            <div id="weather-plugin" class="flex-container flex-center tooltip hide-phone hover-brighten br-15" style="height: 48px; padding-right: 10px; cursor: pointer;" data-tooltip="${tooltipContent}" data-tooltip-placement="bottom">
                <svg width="26px" height="26px" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" style="margin-right: 6px; color: var(--color-4, #fff);">
                    <path d="M14 14.76V3.5a2.5 2.5 0 0 0-5 0v11.26a4.5 4.5 0 1 0 5 0z"></path>
                </svg>
                <span class="color-4 m-0 weather-temp-text" style="font-size: 32px; padding-bottom: 2px; font-weight: 100;">--°</span><br>
            </div>
        `);

        $serverInfoContainer.prepend(weatherPanel);
        
        setTimeout(() => {
            if (typeof initTooltips === 'function') {
                initTooltips(weatherPanel);
            }
        }, 500);

        if ($(window).width() < 768) {
            $serverInfoContainer.attr('style', 'text-align: center !important; padding: 0 !important; width: 100% !important; margin-bottom: 0 !important');
        }
    }

    let lastRenderedSignature = "";

    function renderWeather(obs, isImperial, display, trend, stationModel) {
        const currentSignature = JSON.stringify(obs) + isImperial + JSON.stringify(display) + trend + stationModel;
        
        let existingPlugin = document.getElementById('weather-plugin');

        if (existingPlugin && currentSignature === lastRenderedSignature) {
            return;
        }
        lastRenderedSignature = currentSignature;

        let wasHovered = false;
        if (existingPlugin) {
            wasHovered = $(existingPlugin).is(':hover');
        }

        document.getElementById('weather-plugin')?.remove();

        const unitData = isImperial ? obs.imperial : obs.metric;
        const temp = (unitData.temp !== null && unitData.temp !== undefined) ? unitData.temp : "--";
        const pressure = (unitData.pressure !== null && unitData.pressure !== undefined) ? unitData.pressure : "[Unavailable]";
        const humidity = (obs.humidity !== null && obs.humidity !== undefined) ? `${obs.humidity}%` : "[Unavailable]";

        const tempUnit = isImperial ? '°F' : '°C';
        const pressureUnit = isImperial ? 'inHg' : 'hPa';
        const windUnit = isImperial ? 'mph' : 'km/h';
        const precipUnit = isImperial ? 'in' : 'mm';

        let trendSymbol = "";
        if (trend === "rising") trendSymbol = " ↗";
        else if (trend === "falling") trendSymbol = " ↘";
        else if (trend === "steady") trendSymbol = " →";

        let rowsContent = "";

        if (display.pressure !== false) {
            rowsContent += `
                <tr>
                    <td class='text-bold' style='padding-right: 20px;'>Pressure:</td>
                    <td>${pressure !== "[Unavailable]" ? `${pressure} ${pressureUnit}${trendSymbol}` : "[Unavailable]"}</td>
                </tr>`;
        }

        if (display.humidity !== false) {
            rowsContent += `
                <tr>
                    <td class='text-bold' style='padding-right: 20px;'>Humidity:</td>
                    <td>${humidity}</td>
                </tr>`;
        }

        if (display.dewPoint) {
            const val = (unitData.dewpt !== null && unitData.dewpt !== undefined) ? `${unitData.dewpt} ${tempUnit}` : "[Unavailable]";
            rowsContent += `<tr><td class='text-bold'>Dew Point:</td><td>${val}</td></tr>`;
        }

        if (display.heatIndex_feelsLike) {
            const val = (unitData.heatIndex !== null && unitData.heatIndex !== undefined) ? `${unitData.heatIndex} ${tempUnit}` : "[Unavailable]";
            rowsContent += `<tr><td class='text-bold'>Heat Index:</td><td>${val}</td></tr>`;
        }

        if (display.windChill) {
            const val = (unitData.windChill !== null && unitData.windChill !== undefined) ? `${unitData.windChill} ${tempUnit}` : "[Unavailable]";
            rowsContent += `<tr><td class='text-bold'>Wind Chill:</td><td>${val}</td></tr>`;
        }

        if (display.windAverageSpeed || display.windDirection || display.windGusts) {
            let windText = "";
            if (display.windAverageSpeed) {
                windText += (unitData.windSpeed !== null && unitData.windSpeed !== undefined) ? `${unitData.windSpeed} ${windUnit}` : "[Unavailable]";
            }
            if (display.windDirection) {
                const dirVal = (obs.winddir !== null && obs.winddir !== undefined) ? `${obs.winddir}°` : "[Unavailable]";
                windText += (windText !== "") ? ` (${dirVal})` : dirVal;
            }
            if (display.windGusts) {
                const gustVal = (unitData.windGust !== null && unitData.windGust !== undefined) ? `${unitData.windGust} ${windUnit}` : "[Unavailable]";
                windText += (windText !== "") ? ` / Gusts: ${gustVal}` : `Gusts: ${gustVal}`;
            }
            if (windText !== "") rowsContent += `<tr><td class='text-bold'>Wind:</td><td>${windText}</td></tr>`;
        }

        if (display.precipitationHourlyRate) {
            const val = (unitData.precipRate !== null && unitData.precipRate !== undefined) ? `${unitData.precipRate} ${precipUnit}/h` : "[Unavailable]";
            rowsContent += `<tr><td class='text-bold'>Rain (rate):</td><td>${val}</td></tr>`;
        }

        if (display.precipitationDailyTotal) {
            const val = (unitData.precipTotal !== null && unitData.precipTotal !== undefined) ? `${unitData.precipTotal} ${precipUnit}` : "[Unavailable]";
            rowsContent += `<tr><td class='text-bold'>Rain (daily):</td><td>${val}</td></tr>`;
        }

        if (display.solarRadiation) {
            const val = (obs.solarRadiation !== null && obs.solarRadiation !== undefined) ? `${obs.solarRadiation} W/m²` : "[Unavailable]";
            rowsContent += `<tr><td class='text-bold'>Solar Rad.:</td><td>${val}</td></tr>`;
        }

        if (display.uvIndex) {
            const val = (obs.uv !== null && obs.uv !== undefined) ? `${obs.uv}` : "[Unavailable]";
            rowsContent += `<tr><td class='text-bold'>UV Index:</td><td>${val}</td></tr>`;
        }

        let tooltipContent = "";
        const hasVisibleRows = (rowsContent.trim() !== "");

        if (hasVisibleRows) {
            const headerText = (stationModel && stationModel.trim() !== "") 
                ? `Personal Weather Station: <span style='font-weight: normal; color: inherit;'>${stationModel}</span>`
                : `Personal Weather Station`;

            let updatedTimeRow = "";
            if (obs.obsTimeUtc && obs.obsTimeUtc.includes("T")) {
                const utcTime = obs.obsTimeUtc.split("T")[1].substring(0, 5);
                updatedTimeRow = `
                <tr>
                    <td colspan='2' class='text-gray text-small' style='padding-bottom: 6px; text-align: center;'>
                        Updated at ${utcTime} UTC
                    </td>
                </tr>`;
            }

            tooltipContent = `<table class='text-left'>
                <tr>
                    <td colspan='2' class='text-bold' style='padding-bottom: 2px; text-align: center; color: var(--color-4, #48bb78);'>
                        ${headerText}
                    </td>
                </tr>
                ${updatedTimeRow}
                ${rowsContent}
            </table>`;
        }

        const $serverInfoContainer = $('.dashboard-panel .panel-100-real .dashboard-panel-plugin-content');
        
        const tooltipAttr = hasVisibleRows ? `data-tooltip="${tooltipContent}" data-tooltip-placement="bottom"` : '';
        const tooltipClass = hasVisibleRows ? 'tooltip' : '';

        const weatherPanel = $(`
            <div id="weather-plugin" class="flex-container flex-center ${tooltipClass} hide-phone hover-brighten br-15" style="height: 48px; padding-right: 10px; cursor: pointer;" ${tooltipAttr}>
                <svg width="26px" height="26px" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" style="margin-right: 6px; color: var(--color-4, #fff);">
                    <path d="M14 14.76V3.5a2.5 2.5 0 0 0-5 0v11.26a4.5 4.5 0 1 0 5 0z"></path>
                </svg>
                <span class="color-4 m-0 weather-temp-text" style="font-size: 32px; padding-bottom: 2px; font-weight: 100;">${temp}${tempUnit}</span><br>
            </div>
        `);

        $serverInfoContainer.prepend(weatherPanel);
        
        setTimeout(() => {
            if (hasVisibleRows && typeof initTooltips === 'function') {
                initTooltips(weatherPanel);
            }
            if (wasHovered && hasVisibleRows) {
                weatherPanel.trigger('mouseenter');
            }
        }, 100);

        if ($(window).width() < 768) {
            $serverInfoContainer.attr('style', 'text-align: center !important; padding: 0 !important; width: 100% !important; margin-bottom: 0 !important');
        }
    }

    function startDOMWatcher() {
        const interval = setInterval(() => {
            const target = 
                document.querySelector('.dashboard-panel .panel-100-real .dashboard-panel-plugin-content') ||
                document.querySelector('.dashboard-panel-plugin-content') ||
                document.querySelector('.panel-100-real');

            if (target) {
                clearInterval(interval);
                renderNoData();
                initWebSocket();
            }
        }, 500);
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', startDOMWatcher);
    } else {
        startDOMWatcher();
    }
})();